#pragma once
// =============================================================
// Wind Waker Static Recompilation - Common header for recompiled code
// Auto-generated support macros and helpers
// DO NOT EDIT - Generated by ww_recompiler
// =============================================================

#include "ww/runtime.h"
#include "gcrecomp/ppc_helpers.h"
#include <cmath>
#include <cstring>

using namespace ww;

// Memory access macros
#define MEM_READ8(addr)        g_mem.read8(addr)
#define MEM_READ16(addr)       g_mem.read16(addr)
#define MEM_READ32(addr)       g_mem.read32(addr)
#define MEM_READF32(addr)      g_mem.readf32(addr)
#define MEM_READF64(addr)      g_mem.readf64(addr)
#define MEM_WRITE8(addr, v)    g_mem.write8(addr, v)
#define MEM_WRITE16(addr, v)   g_mem.write16(addr, v)
#define MEM_WRITE32(addr, v)   g_mem.write32(addr, v)
#define MEM_WRITEF32(addr, v)  g_mem.writef32(addr, v)
#define MEM_WRITEF64(addr, v)  g_mem.writef64(addr, v)

// Indirect call/jump
#define CALL_INDIRECT(addr, ctx, mem) g_func_table.call(addr, ctx, mem)
#define JUMP_INDIRECT(addr) { /* TODO: switch table */ }

// PSQ wrapper macros — delegate to gcrecomp's ppc_helpers.h functions,
// passing the ww::g_mem instance.
#define PSQ_LOAD_ONE(addr, gqr)              psq_load_one(g_mem, addr, gqr)
#define PSQ_LOAD_PAIR(ps0, ps1, addr, gqr)   psq_load_pair(g_mem, ps0, ps1, addr, gqr)
#define PSQ_STORE_ONE(val, addr, gqr)         psq_store_one(g_mem, val, addr, gqr)
#define PSQ_STORE_PAIR(v0, v1, addr, gqr)     psq_store_pair(g_mem, v0, v1, addr, gqr)
