#ifndef F_PC_NAME_H_
#define F_PC_NAME_H_

#include "global.h"

#if VERSION != VERSION_WII_USA_R0 && VERSION != VERSION_WII_PAL
#define PROCS_NOT_WII \
/* 0x00F */ X(fpcNm_WARNING_SCENE_e) \
/* 0x010 */ X(fpcNm_WARNING2_SCENE_e)
#else
#define PROCS_NOT_WII
#endif

#define ALL_PROCS \
/* 0x000 */ X(fpcNm_OVERLAP0_e) \
/* 0x001 */ X(fpcNm_OVERLAP1_e) \
/* 0x002 */ X(fpcNm_OVERLAP3_e) \
/* 0x003 */ X(fpcNm_OVERLAP6_e) \
/* 0x004 */ X(fpcNm_OVERLAP7_e) \
/* 0x005 */ X(fpcNm_OVERLAP8_e) \
/* 0x006 */ X(fpcNm_OVERLAP9_e) \
/* 0x007 */ X(fpcNm_OVERLAP10_e) \
/* 0x008 */ X(fpcNm_OVERLAP11_e) \
/* 0x009 */ X(fpcNm_LOGO_SCENE_e) \
/* 0x00A */ X(fpcNm_MENU_SCENE_e) \
/* 0x00B */ X(fpcNm_PLAY_SCENE_e) \
/* 0x00C */ X(fpcNm_OPENING_SCENE_e) \
/* 0x00D */ X(fpcNm_NAME_SCENE_e) \
/* 0x00E */ X(fpcNm_NAMEEX_SCENE_e) \
PROCS_NOT_WII \
/* 0x011 */ X(fpcNm_OVERLAP2_e) \
/* 0x012 */ X(fpcNm_ROOM_SCENE_e) \
/* 0x013 */ X(fpcNm_KANKYO_e) \
/* 0x014 */ X(fpcNm_ALLDIE_e) \
/* 0x015 */ X(fpcNm_ENVSE_e) \
/* 0x016 */ X(fpcNm_Obj_Swpush_e) \
/* 0x017 */ X(fpcNm_Obj_Swpush2_e) \
/* 0x018 */ X(fpcNm_Obj_Swpush5_e) \
/* 0x019 */ X(fpcNm_Tag_Gstart_e) \
/* 0x01A */ X(fpcNm_NO_CHG_ROOM_e) \
/* 0x01B */ X(fpcNm_Obj_Lv6ElevtA_e) \
/* 0x01C */ X(fpcNm_OBJ_SO_e) \
/* 0x01D */ X(fpcNm_Obj_Movebox_e) \
/* 0x01E */ X(fpcNm_Obj_SwTurn_e) \
/* 0x01F */ X(fpcNm_Obj_Lv6SwTurn_e) \
/* 0x020 */ X(fpcNm_OBJ_SEKIZOA_e) \
/* 0x021 */ X(fpcNm_OBJ_GRA_e) \
/* 0x022 */ X(fpcNm_TAG_GRA_e) \
/* 0x023 */ X(fpcNm_TAG_YAMI_e) \
/* 0x024 */ X(fpcNm_Obj_Ladder_e) \
/* 0x025 */ X(fpcNm_OBJ_BEF_e) \
/* 0x026 */ X(fpcNm_OBJ_FMOBJ_e) \
/* 0x027 */ X(fpcNm_OBJ_LBOX_e) \
/* 0x028 */ X(fpcNm_OBJ_WEB0_e) \
/* 0x029 */ X(fpcNm_OBJ_WEB1_e) \
/* 0x02A */ X(fpcNm_OBJ_CB_e) \
/* 0x02B */ X(fpcNm_OBJ_MAKI_e) \
/* 0x02C */ X(fpcNm_OBJ_BRG_e) \
/* 0x02D */ X(fpcNm_OBJ_GB_e) \
/* 0x02E */ X(fpcNm_OBJ_GM_e) \
/* 0x02F */ X(fpcNm_OBJ_TOBY_e) \
/* 0x030 */ X(fpcNm_OBJ_TP_e) \
/* 0x031 */ X(fpcNm_TREESH_e) \
/* 0x032 */ X(fpcNm_Obj_ZDoor_e) \
/* 0x033 */ X(fpcNm_Obj_Pillar_e) \
/* 0x034 */ X(fpcNm_Obj_Cdoor_e) \
/* 0x035 */ X(fpcNm_GRDWATER_e) \
/* 0x036 */ X(fpcNm_Obj_RotBridge_e) \
/* 0x037 */ X(fpcNm_Obj_MagLift_e) \
/* 0x038 */ X(fpcNm_Obj_MagLiftRot_e) \
/* 0x039 */ X(fpcNm_Obj_Lv1Cdl00_e) \
/* 0x03A */ X(fpcNm_Obj_Lv1Cdl01_e) \
/* 0x03B */ X(fpcNm_Obj_TvCdlst_e) \
/* 0x03C */ X(fpcNm_Obj_HsTarget_e) \
/* 0x03D */ X(fpcNm_Obj_HeavySw_e) \
/* 0x03E */ X(fpcNm_Obj_GoGate_e) \
/* 0x03F */ X(fpcNm_Obj_TaFence_e) \
/* 0x040 */ X(fpcNm_Obj_Saidan_e) \
/* 0x041 */ X(fpcNm_Obj_SpinLift_e) \
/* 0x042 */ X(fpcNm_Obj_BmWindow_e) \
/* 0x043 */ X(fpcNm_Obj_RfHole_e) \
/* 0x044 */ X(fpcNm_Obj_WaterPillar_e) \
/* 0x045 */ X(fpcNm_Obj_SyRock_e) \
/* 0x046 */ X(fpcNm_Obj_BsGate_e) \
/* 0x047 */ X(fpcNm_Obj_AmiShutter_e) \
/* 0x048 */ X(fpcNm_Obj_WtGate_e) \
/* 0x049 */ X(fpcNm_Obj_Lv2Candle_e) \
/* 0x04A */ X(fpcNm_Obj_TogeTrap_e) \
/* 0x04B */ X(fpcNm_Obj_RotTrap_e) \
/* 0x04C */ X(fpcNm_Obj_SwallShutter_e) \
/* 0x04D */ X(fpcNm_Obj_IceWall_e) \
/* 0x04E */ X(fpcNm_Obj_Lv5SwIce_e) \
/* 0x04F */ X(fpcNm_Obj_Lv5FBoard_e) \
/* 0x050 */ X(fpcNm_Obj_Turara_e) \
/* 0x051 */ X(fpcNm_Obj_TwGate_e) \
/* 0x052 */ X(fpcNm_Obj_Digholl_e) \
/* 0x053 */ X(fpcNm_Obj_Digpl_e) \
/* 0x054 */ X(fpcNm_Obj_TestCube_e) \
/* 0x055 */ X(fpcNm_Obj_Kshutter_e) \
/* 0x056 */ X(fpcNm_NPC_COACH_e) \
/* 0x057 */ X(fpcNm_NPC_THEB_e) \
/* 0x058 */ X(fpcNm_COACH_FIRE_e) \
/* 0x059 */ X(fpcNm_COACH2D_e) \
/* 0x05A */ X(fpcNm_BALLOON2D_e) \
/* 0x05B */ X(fpcNm_SKIP2D_e) \
/* 0x05C */ X(fpcNm_Obj_MvStair_e) \
/* 0x05D */ X(fpcNm_Obj_Cowdoor_e) \
/* 0x05E */ X(fpcNm_Obj_Swpropeller_e) \
/* 0x05F */ X(fpcNm_Obj_BoomShutter_e) \
/* 0x060 */ X(fpcNm_NPC_KS_e) \
/* 0x061 */ X(fpcNm_Obj_Hfuta_e) \
/* 0x062 */ X(fpcNm_Obj_BkDoor_e) \
/* 0x063 */ X(fpcNm_Obj_Cboard_e) \
/* 0x064 */ X(fpcNm_Obj_MGate_e) \
/* 0x065 */ X(fpcNm_Obj_Ikada_e) \
/* 0x066 */ X(fpcNm_Obj_Ice_l_e) \
/* 0x067 */ X(fpcNm_Obj_Ice_s_e) \
/* 0x068 */ X(fpcNm_Obj_E_CREATE_e) \
/* 0x069 */ X(fpcNm_Obj_Bhbridge_e) \
/* 0x06A */ X(fpcNm_Obj_Kaisou_e) \
/* 0x06B */ X(fpcNm_Obj_HHASHI_e) \
/* 0x06C */ X(fpcNm_Obj_BHASHI_e) \
/* 0x06D */ X(fpcNm_OCTHASHI_e) \
/* 0x06E */ X(fpcNm_Obj_THASHI_e) \
/* 0x06F */ X(fpcNm_Obj_CRVGATE_e) \
/* 0x070 */ X(fpcNm_Obj_CRVFENCE_e) \
/* 0x071 */ X(fpcNm_Obj_CRVHAHEN_e) \
/* 0x072 */ X(fpcNm_Obj_CRVSTEEL_e) \
/* 0x073 */ X(fpcNm_Obj_CRVLH_UP_e) \
/* 0x074 */ X(fpcNm_Obj_CRVLH_DW_e) \
/* 0x075 */ X(fpcNm_Obj_RIVERROCK_e) \
/* 0x076 */ X(fpcNm_Obj_DUST_e) \
/* 0x077 */ X(fpcNm_Obj_ITA_e) \
/* 0x078 */ X(fpcNm_Obj_Window_e) \
/* 0x079 */ X(fpcNm_Obj_MetalBox_e) \
/* 0x07A */ X(fpcNm_Obj_BBox_e) \
/* 0x07B */ X(fpcNm_OBJ_MSIMA_e) \
/* 0x07C */ X(fpcNm_OBJ_MYOGAN_e) \
/* 0x07D */ X(fpcNm_B_ZANTS_e) \
/* 0x07E */ X(fpcNm_Obj_ChainBlock_e) \
/* 0x07F */ X(fpcNm_Obj_ChainWall_e) \
/* 0x080 */ X(fpcNm_Obj_KkrGate_e) \
/* 0x081 */ X(fpcNm_Obj_RiderGate_e) \
/* 0x082 */ X(fpcNm_Obj_Onsen_e) \
/* 0x083 */ X(fpcNm_Obj_Chest_e) \
/* 0x084 */ X(fpcNm_Obj_Bemos_e) \
/* 0x085 */ X(fpcNm_Obj_RopeBridge_e) \
/* 0x086 */ X(fpcNm_Obj_WellCover_e) \
/* 0x087 */ X(fpcNm_Obj_GraveStone_e) \
/* 0x088 */ X(fpcNm_Obj_ZraRock_e) \
/* 0x089 */ X(fpcNm_Obj_GraRock_e) \
/* 0x08A */ X(fpcNm_Obj_GrzRock_e) \
/* 0x08B */ X(fpcNm_GRA_WALL_e) \
/* 0x08C */ X(fpcNm_OBJ_ONSEN_FIRE_e) \
/* 0x08D */ X(fpcNm_Obj_Lv6bemos_e) \
/* 0x08E */ X(fpcNm_Obj_Lv6bemos2_e) \
/* 0x08F */ X(fpcNm_Obj_BarDesk_e) \
/* 0x090 */ X(fpcNm_Obj_DigSnow_e) \
/* 0x091 */ X(fpcNm_Obj_Ytaihou_e) \
/* 0x092 */ X(fpcNm_Obj_Elevator_e) \
/* 0x093 */ X(fpcNm_Obj_Lv6TogeRoll_e) \
/* 0x094 */ X(fpcNm_Obj_Lv6TogeTrap_e) \
/* 0x095 */ X(fpcNm_Obj_Lv6Tenbin_e) \
/* 0x096 */ X(fpcNm_Obj_Lv6SwGate_e) \
/* 0x097 */ X(fpcNm_Obj_Lv6Lblock_e) \
/* 0x098 */ X(fpcNm_Obj_Lv6ChgGate_e) \
/* 0x099 */ X(fpcNm_Obj_Lv6FuriTrap_e) \
/* 0x09A */ X(fpcNm_Obj_Lv6SzGate_e) \
/* 0x09B */ X(fpcNm_Obj_Lv4EdShutter_e) \
/* 0x09C */ X(fpcNm_Obj_Lv4Gate_e) \
/* 0x09D */ X(fpcNm_Obj_Lv4PoGate_e) \
/* 0x09E */ X(fpcNm_Obj_Lv4SlideWall_e) \
/* 0x09F */ X(fpcNm_Obj_Lv4HsTarget_e) \
/* 0x0A0 */ X(fpcNm_Obj_Lv7PropY_e) \
/* 0x0A1 */ X(fpcNm_Obj_Lv7BsGate_e) \
/* 0x0A2 */ X(fpcNm_Obj_Lv8OptiLift_e) \
/* 0x0A3 */ X(fpcNm_Obj_Lv8KekkaiTrap_e) \
/* 0x0A4 */ X(fpcNm_Obj_Lv8Lift_e) \
/* 0x0A5 */ X(fpcNm_Obj_Lv8UdFloor_e) \
/* 0x0A6 */ X(fpcNm_Obj_Lv9SwShutter_e) \
/* 0x0A7 */ X(fpcNm_Obj_TobyHouse_e) \
/* 0x0A8 */ X(fpcNm_Obj_poCandle_e) \
/* 0x0A9 */ X(fpcNm_Obj_Lv4DigSand_e) \
/* 0x0AA */ X(fpcNm_Obj_FallObj_e) \
/* 0x0AB */ X(fpcNm_Obj_SmgDoor_e) \
/* 0x0AC */ X(fpcNm_Obj_SwLight_e) \
/* 0x0AD */ X(fpcNm_Obj_Avalanche_e) \
/* 0x0AE */ X(fpcNm_Obj_MirrorScrew_e) \
/* 0x0AF */ X(fpcNm_Obj_MirrorSand_e) \
/* 0x0B0 */ X(fpcNm_Obj_MirrorTable_e) \
/* 0x0B1 */ X(fpcNm_Obj_MirrorChain_e) \
/* 0x0B2 */ X(fpcNm_Obj_Mirror6Pole_e) \
/* 0x0B3 */ X(fpcNm_Obj_SwSpinner_e) \
/* 0x0B4 */ X(fpcNm_Obj_TDoor_e) \
/* 0x0B5 */ X(fpcNm_Obj_Lv7Bridge_e) \
/* 0x0B6 */ X(fpcNm_Obj_zrTurara_e) \
/* 0x0B7 */ X(fpcNm_Obj_TakaraDai_e) \
/* 0x0B8 */ X(fpcNm_Obj_Table_e) \
/* 0x0B9 */ X(fpcNm_Obj_CatDoor_e) \
/* 0x0BA */ X(fpcNm_Obj_Gake_e) \
/* 0x0BB */ X(fpcNm_CSTAF_e) \
/* 0x0BC */ X(fpcNm_Obj_Lv4RailWall_e) \
/* 0x0BD */ X(fpcNm_Obj_Lv4Sand_e) \
/* 0x0BE */ X(fpcNm_Obj_PushDoor_e) \
/* 0x0BF */ X(fpcNm_PushDoor_e) \
/* 0x0C0 */ X(fpcNm_Obj_GanonWall2_e) \
/* 0x0C1 */ X(fpcNm_Obj_Lv4Bridge_e) \
/* 0x0C2 */ X(fpcNm_Obj_Lv4Floor_e) \
/* 0x0C3 */ X(fpcNm_Tag_Spinner_e) \
/* 0x0C4 */ X(fpcNm_Obj_SwHang_e) \
/* 0x0C5 */ X(fpcNm_Obj_RotStair_e) \
/* 0x0C6 */ X(fpcNm_Obj_MagneArm_e) \
/* 0x0C7 */ X(fpcNm_Obj_KWheel00_e) \
/* 0x0C8 */ X(fpcNm_Obj_KWheel01_e) \
/* 0x0C9 */ X(fpcNm_Obj_Ychndlr_e) \
/* 0x0CA */ X(fpcNm_Obj_PRElvtr_e) \
/* 0x0CB */ X(fpcNm_Obj_MHasu_e) \
/* 0x0CC */ X(fpcNm_Obj_YIblltray_e) \
/* 0x0CD */ X(fpcNm_Obj_Lv6EGate_e) \
/* 0x0CE */ X(fpcNm_Obj_PDtile_e) \
/* 0x0CF */ X(fpcNm_Obj_PDwall_e) \
/* 0x0D0 */ X(fpcNm_Obj_Lv4PRwall_e) \
/* 0x0D1 */ X(fpcNm_Obj_KLift00_e) \
/* 0x0D2 */ X(fpcNm_B_OH_e) \
/* 0x0D3 */ X(fpcNm_Obj_Lv4Chan_e) \
/* 0x0D4 */ X(fpcNm_Obj_Lv3R10Saka_e) \
/* 0x0D5 */ X(fpcNm_Obj_Lv3Water_e) \
/* 0x0D6 */ X(fpcNm_Obj_Lv3Water2_e) \
/* 0x0D7 */ X(fpcNm_OBJ_LV3WATERB_e) \
/* 0x0D8 */ X(fpcNm_Obj_HBombkoya_e) \
/* 0x0D9 */ X(fpcNm_Obj_SZbridge_e) \
/* 0x0DA */ X(fpcNm_Obj_KakarikoBrg_e) \
/* 0x0DB */ X(fpcNm_Obj_OrdinBrg_e) \
/* 0x0DC */ X(fpcNm_Obj_BurnBox_e) \
/* 0x0DD */ X(fpcNm_Obj_KJgjs_e) \
/* 0x0DE */ X(fpcNm_OBJ_IHASI_e) \
/* 0x0DF */ X(fpcNm_Obj_IceBlock_e) \
/* 0x0E0 */ X(fpcNm_Obj_VolcanicBall_e) \
/* 0x0E1 */ X(fpcNm_Obj_VolcanicBomb_e) \
/* 0x0E2 */ X(fpcNm_Obj_VolcGnd_e) \
/* 0x0E3 */ X(fpcNm_Obj_KKanban_e) \
/* 0x0E4 */ X(fpcNm_E_PH_e) \
/* 0x0E5 */ X(fpcNm_NPC_ZRA_e) \
/* 0x0E6 */ X(fpcNm_Obj_Chandelier_e) \
/* 0x0E7 */ X(fpcNm_Obj_Stopper2_e) \
/* 0x0E8 */ X(fpcNm_DOOR20_e) \
/* 0x0E9 */ X(fpcNm_Tag_Hinit_e) \
/* 0x0EA */ X(fpcNm_Tag_Hjump_e) \
/* 0x0EB */ X(fpcNm_Tag_AJnot_e) \
/* 0x0EC */ X(fpcNm_Tag_Hstop_e) \
/* 0x0ED */ X(fpcNm_CANOE_e) \
/* 0x0EE */ X(fpcNm_HORSE_e) \
/* 0x0EF */ X(fpcNm_E_WB_e) \
/* 0x0F0 */ X(fpcNm_OBJ_ITO_e) \
/* 0x0F1 */ X(fpcNm_OBJ_SW_e) \
/* 0x0F2 */ X(fpcNm_SPINNER_e) \
/* 0x0F3 */ X(fpcNm_B_OB_e) \
/* 0x0F4 */ X(fpcNm_KAGO_e) \
/* 0x0F5 */ X(fpcNm_E_YC_e) \
/* 0x0F6 */ X(fpcNm_B_DS_e) \
/* 0x0F7 */ X(fpcNm_B_DR_e) \
/* 0x0F8 */ X(fpcNm_B_ZANTZ_e) \
/* 0x0F9 */ X(fpcNm_B_ZANT_e) \
/* 0x0FA */ X(fpcNm_B_ZANTM_e) \
/* 0x0FB */ X(fpcNm_TBOX_e) \
/* 0x0FC */ X(fpcNm_TBOX2_e) \
/* 0x0FD */ X(fpcNm_ALINK_e) \
/* 0x0FE */ X(fpcNm_BOOMERANG_e) \
/* 0x0FF */ X(fpcNm_MIDNA_e) \
/* 0x100 */ X(fpcNm_NPC_TK_e) \
/* 0x101 */ X(fpcNm_NPC_WORM_e) \
/* 0x102 */ X(fpcNm_PPolamp_e) \
/* 0x103 */ X(fpcNm_BkyRock_e) \
/* 0x104 */ X(fpcNm_HITOBJ_e) \
/* 0x105 */ X(fpcNm_EP_e) \
/* 0x106 */ X(fpcNm_COW_e) \
/* 0x107 */ X(fpcNm_PERU_e) \
/* 0x108 */ X(fpcNm_NI_e) \
/* 0x109 */ X(fpcNm_NPC_TKJ2_e) \
/* 0x10A */ X(fpcNm_SQ_e) \
/* 0x10B */ X(fpcNm_NPC_SQ_e) \
/* 0x10C */ X(fpcNm_DO_e) \
/* 0x10D */ X(fpcNm_NPC_NE_e) \
/* 0x10E */ X(fpcNm_NPC_TR_e) \
/* 0x10F */ X(fpcNm_NPC_LF_e) \
/* 0x110 */ X(fpcNm_OBJ_FOOD_e) \
/* 0x111 */ X(fpcNm_OBJ_KI_e) \
/* 0x112 */ X(fpcNm_OBJ_KITA_e) \
/* 0x113 */ X(fpcNm_OBJ_KEY_e) \
/* 0x114 */ X(fpcNm_OBJ_KEYHOLE_e) \
/* 0x115 */ X(fpcNm_Obj_Lv5Key_e) \
/* 0x116 */ X(fpcNm_OBJ_LP_e) \
/* 0x117 */ X(fpcNm_OBJ_TATIGI_e) \
/* 0x118 */ X(fpcNm_OBJ_ROCK_e) \
/* 0x119 */ X(fpcNm_OBJ_WFLAG_e) \
/* 0x11A */ X(fpcNm_OBJ_KAGE_e) \
/* 0x11B */ X(fpcNm_OBJ_KANBAN2_e) \
/* 0x11C */ X(fpcNm_OBJ_BALLOON_e) \
/* 0x11D */ X(fpcNm_OBJ_SUISYA_e) \
/* 0x11E */ X(fpcNm_OBJ_OILTUBO_e) \
/* 0x11F */ X(fpcNm_OBJ_ROTEN_e) \
/* 0x120 */ X(fpcNm_OBJ_SSDRINK_e) \
/* 0x121 */ X(fpcNm_OBJ_SSITEM_e) \
/* 0x122 */ X(fpcNm_TAG_SSDRINK_e) \
/* 0x123 */ X(fpcNm_TAG_BTLITM_e) \
/* 0x124 */ X(fpcNm_TAG_LV5SOUP_e) \
/* 0x125 */ X(fpcNm_TAG_MNLIGHT_e) \
/* 0x126 */ X(fpcNm_TAG_SHOPCAM_e) \
/* 0x127 */ X(fpcNm_TAG_SHOPITM_e) \
/* 0x128 */ X(fpcNm_OBJ_NDOOR_e) \
/* 0x129 */ X(fpcNm_OBJ_UDOOR_e) \
/* 0x12A */ X(fpcNm_OBJ_USAKU_e) \
/* 0x12B */ X(fpcNm_Obj_SM_DOOR_e) \
/* 0x12C */ X(fpcNm_OBJ_BED_e) \
/* 0x12D */ X(fpcNm_OBJ_BOUMATO_e) \
/* 0x12E */ X(fpcNm_OBJ_ITAMATO_e) \
/* 0x12F */ X(fpcNm_OBJ_NOUGU_e) \
/* 0x130 */ X(fpcNm_OBJ_STICK_e) \
/* 0x131 */ X(fpcNm_OBJ_MIE_e) \
/* 0x132 */ X(fpcNm_OBJ_SEKIDOOR_e) \
/* 0x133 */ X(fpcNm_OBJ_SEKIZO_e) \
/* 0x134 */ X(fpcNm_OBJ_SMTILE_e) \
/* 0x135 */ X(fpcNm_NPC_FISH_e) \
/* 0x136 */ X(fpcNm_MG_FISH_e) \
/* 0x137 */ X(fpcNm_FSHOP_e) \
/* 0x138 */ X(fpcNm_NPC_DU_e) \
/* 0x139 */ X(fpcNm_DISAPPEAR_e) \
/* 0x13A */ X(fpcNm_Obj_Mato_e) \
/* 0x13B */ X(fpcNm_Obj_Flag_e) \
/* 0x13C */ X(fpcNm_Obj_Flag2_e) \
/* 0x13D */ X(fpcNm_Obj_Flag3_e) \
/* 0x13E */ X(fpcNm_Obj_GOMIKABE_e) \
/* 0x13F */ X(fpcNm_Obj_Yousei_e) \
/* 0x140 */ X(fpcNm_Obj_Kabuto_e) \
/* 0x141 */ X(fpcNm_Obj_Cho_e) \
/* 0x142 */ X(fpcNm_Obj_Kuw_e) \
/* 0x143 */ X(fpcNm_Obj_Nan_e) \
/* 0x144 */ X(fpcNm_Obj_Dan_e) \
/* 0x145 */ X(fpcNm_Obj_Kam_e) \
/* 0x146 */ X(fpcNm_Obj_Ten_e) \
/* 0x147 */ X(fpcNm_Obj_Ari_e) \
/* 0x148 */ X(fpcNm_Obj_Kag_e) \
/* 0x149 */ X(fpcNm_Obj_Batta_e) \
/* 0x14A */ X(fpcNm_Obj_Tombo_e) \
/* 0x14B */ X(fpcNm_Obj_Kat_e) \
/* 0x14C */ X(fpcNm_Obj_H_Saku_e) \
/* 0x14D */ X(fpcNm_Obj_Yobikusa_e) \
/* 0x14E */ X(fpcNm_Obj_KazeNeko_e) \
/* 0x14F */ X(fpcNm_Obj_KznkArm_e) \
/* 0x150 */ X(fpcNm_Obj_NamePlate_e) \
/* 0x151 */ X(fpcNm_Obj_OnCloth_e) \
/* 0x152 */ X(fpcNm_Obj_LndRope_e) \
/* 0x153 */ X(fpcNm_Obj_ItaRope_e) \
/* 0x154 */ X(fpcNm_Obj_Sakuita_e) \
/* 0x155 */ X(fpcNm_Obj_Laundry_e) \
/* 0x156 */ X(fpcNm_WarpBug_e) \
/* 0x157 */ X(fpcNm_Izumi_Gate_e) \
/* 0x158 */ X(fpcNm_Obj_Fchain_e) \
/* 0x159 */ X(fpcNm_Obj_Wchain_e) \
/* 0x15A */ X(fpcNm_Tag_Attp_e) \
/* 0x15B */ X(fpcNm_Obj_Tornado_e) \
/* 0x15C */ X(fpcNm_Obj_Tornado2_e) \
/* 0x15D */ X(fpcNm_Obj_FirePillar_e) \
/* 0x15E */ X(fpcNm_Obj_FirePillar2_e) \
/* 0x15F */ X(fpcNm_Obj_InoBone_e) \
/* 0x160 */ X(fpcNm_Obj_Stopper_e) \
/* 0x161 */ X(fpcNm_Obj_MHole_e) \
/* 0x162 */ X(fpcNm_Tag_Magne_e) \
/* 0x163 */ X(fpcNm_Obj_BossWarp_e) \
/* 0x164 */ X(fpcNm_Obj_WoodPendulum_e) \
/* 0x165 */ X(fpcNm_Obj_WdStick_e) \
/* 0x166 */ X(fpcNm_Obj_StairBlock_e) \
/* 0x167 */ X(fpcNm_Obj_Geyser_e) \
/* 0x168 */ X(fpcNm_Tag_KtOnFire_e) \
/* 0x169 */ X(fpcNm_Obj_FireWood_e) \
/* 0x16A */ X(fpcNm_Obj_FireWood2_e) \
/* 0x16B */ X(fpcNm_Obj_GpTaru_e) \
/* 0x16C */ X(fpcNm_Obj_OnsenTaru_e) \
/* 0x16D */ X(fpcNm_Obj_KiPot_e) \
/* 0x16E */ X(fpcNm_TBOX_SW_e) \
/* 0x16F */ X(fpcNm_Obj_SwChain_e) \
/* 0x170 */ X(fpcNm_Obj_WoodenSword_e) \
/* 0x171 */ X(fpcNm_Obj_StoneMark_e) \
/* 0x172 */ X(fpcNm_Obj_Lv3Candle_e) \
/* 0x173 */ X(fpcNm_Tag_Lv4Candle_e) \
/* 0x174 */ X(fpcNm_Tag_Lv4CandleDm_e) \
/* 0x175 */ X(fpcNm_Obj_DamCps_e) \
/* 0x176 */ X(fpcNm_Obj_Smoke_e) \
/* 0x177 */ X(fpcNm_Obj_WaterFall_e) \
/* 0x178 */ X(fpcNm_Obj_ZoraCloth_e) \
/* 0x179 */ X(fpcNm_Obj_poFire_e) \
/* 0x17A */ X(fpcNm_Tag_poFire_e) \
/* 0x17B */ X(fpcNm_Obj_glowSphere_e) \
/* 0x17C */ X(fpcNm_Tag_LightBall_e) \
/* 0x17D */ X(fpcNm_SwLBall_e) \
/* 0x17E */ X(fpcNm_SwBall_e) \
/* 0x17F */ X(fpcNm_Obj_WaterEff_e) \
/* 0x180 */ X(fpcNm_Tag_RiverBack_e) \
/* 0x181 */ X(fpcNm_Tag_KagoFall_e) \
/* 0x182 */ X(fpcNm_Tag_Lv2PrChk_e) \
/* 0x183 */ X(fpcNm_Obj_Lv4Gear_e) \
/* 0x184 */ X(fpcNm_Obj_MasterSword_e) \
/* 0x185 */ X(fpcNm_Obj_WoodStatue_e) \
/* 0x186 */ X(fpcNm_Obj_Fan_e) \
/* 0x187 */ X(fpcNm_Obj_IceLeaf_e) \
/* 0x188 */ X(fpcNm_Obj_zrTuraraRc_e) \
/* 0x189 */ X(fpcNm_Tag_RetRoom_e) \
/* 0x18A */ X(fpcNm_Obj_WindStone_e) \
/* 0x18B */ X(fpcNm_Tag_WaraHowl_e) \
/* 0x18C */ X(fpcNm_Obj_SCannon_e) \
/* 0x18D */ X(fpcNm_Obj_SmWStone_e) \
/* 0x18E */ X(fpcNm_Obj_SCannonCrs_e) \
/* 0x18F */ X(fpcNm_Tag_SnowEff_e) \
/* 0x190 */ X(fpcNm_Tag_CstaSw_e) \
/* 0x191 */ X(fpcNm_Tag_Lv6CstaSw_e) \
/* 0x192 */ X(fpcNm_Obj_awaPlar_e) \
/* 0x193 */ X(fpcNm_Obj_poTbox_e) \
/* 0x194 */ X(fpcNm_Obj_TimeFire_e) \
/* 0x195 */ X(fpcNm_Obj_TMoon_e) \
/* 0x196 */ X(fpcNm_Obj_GanonWall_e) \
/* 0x197 */ X(fpcNm_Obj_Prop_e) \
/* 0x198 */ X(fpcNm_CSTATUE_e) \
/* 0x199 */ X(fpcNm_Obj_SwBallA_e) \
/* 0x19A */ X(fpcNm_Obj_SwBallB_e) \
/* 0x19B */ X(fpcNm_Obj_SnowSoup_e) \
/* 0x19C */ X(fpcNm_Obj_Nagaisu_e) \
/* 0x19D */ X(fpcNm_Obj_RCircle_e) \
/* 0x19E */ X(fpcNm_Obj_Picture_e) \
/* 0x19F */ X(fpcNm_Tag_SetBall_e) \
/* 0x1A0 */ X(fpcNm_Tag_SmkEmt_e) \
/* 0x1A1 */ X(fpcNm_SwTime_e) \
/* 0x1A2 */ X(fpcNm_Obj_HFtr_e) \
/* 0x1A3 */ X(fpcNm_Obj_HBarrel_e) \
/* 0x1A4 */ X(fpcNm_Obj_Crystal_e) \
/* 0x1A5 */ X(fpcNm_Obj_SCannonTen_e) \
/* 0x1A6 */ X(fpcNm_Obj_SwBallC_e) \
/* 0x1A7 */ X(fpcNm_SCENE_EXIT2_e) \
/* 0x1A8 */ X(fpcNm_Obj_Hata_e) \
/* 0x1A9 */ X(fpcNm_Obj_ToaruMaki_e) \
/* 0x1AA */ X(fpcNm_Tag_AttackItem_e) \
/* 0x1AB */ X(fpcNm_Tag_RmbitSw_e) \
/* 0x1AC */ X(fpcNm_Obj_Sword_e) \
/* 0x1AD */ X(fpcNm_Tag_Spring_e) \
/* 0x1AE */ X(fpcNm_Tag_Statue_e) \
/* 0x1AF */ X(fpcNm_E_AI_e) \
/* 0x1B0 */ X(fpcNm_E_GS_e) \
/* 0x1B1 */ X(fpcNm_E_GOB_e) \
/* 0x1B2 */ X(fpcNm_E_DD_e) \
/* 0x1B3 */ X(fpcNm_E_DN_e) \
/* 0x1B4 */ X(fpcNm_E_S1_e) \
/* 0x1B5 */ X(fpcNm_E_MF_e) \
/* 0x1B6 */ X(fpcNm_E_SG_e) \
/* 0x1B7 */ X(fpcNm_E_BS_e) \
/* 0x1B8 */ X(fpcNm_E_SF_e) \
/* 0x1B9 */ X(fpcNm_E_SH_e) \
/* 0x1BA */ X(fpcNm_E_DF_e) \
/* 0x1BB */ X(fpcNm_E_GM_e) \
/* 0x1BC */ X(fpcNm_E_MD_e) \
/* 0x1BD */ X(fpcNm_E_SM_e) \
/* 0x1BE */ X(fpcNm_E_SM2_e) \
/* 0x1BF */ X(fpcNm_E_ST_e) \
/* 0x1C0 */ X(fpcNm_E_ST_LINE_e) \
/* 0x1C1 */ X(fpcNm_E_SB_e) \
/* 0x1C2 */ X(fpcNm_E_TH_e) \
/* 0x1C3 */ X(fpcNm_E_CR_e) \
/* 0x1C4 */ X(fpcNm_E_CR_EGG_e) \
/* 0x1C5 */ X(fpcNm_E_DB_e) \
/* 0x1C6 */ X(fpcNm_E_DB_LEAF_e) \
/* 0x1C7 */ X(fpcNm_E_GA_e) \
/* 0x1C8 */ X(fpcNm_E_GB_e) \
/* 0x1C9 */ X(fpcNm_E_HB_e) \
/* 0x1CA */ X(fpcNm_E_HB_LEAF_e) \
/* 0x1CB */ X(fpcNm_E_HZELDA_e) \
/* 0x1CC */ X(fpcNm_E_YD_e) \
/* 0x1CD */ X(fpcNm_E_YH_e) \
/* 0x1CE */ X(fpcNm_E_YD_LEAF_e) \
/* 0x1CF */ X(fpcNm_E_HM_e) \
/* 0x1D0 */ X(fpcNm_E_TK_e) \
/* 0x1D1 */ X(fpcNm_E_TK2_e) \
/* 0x1D2 */ X(fpcNm_E_TK_BALL_e) \
/* 0x1D3 */ X(fpcNm_E_RB_e) \
/* 0x1D4 */ X(fpcNm_E_RD_e) \
/* 0x1D5 */ X(fpcNm_E_RDB_e) \
/* 0x1D6 */ X(fpcNm_E_RDY_e) \
/* 0x1D7 */ X(fpcNm_E_FM_e) \
/* 0x1D8 */ X(fpcNm_E_FS_e) \
/* 0x1D9 */ X(fpcNm_E_PM_e) \
/* 0x1DA */ X(fpcNm_E_PO_e) \
/* 0x1DB */ X(fpcNm_E_MB_e) \
/* 0x1DC */ X(fpcNm_E_MK_e) \
/* 0x1DD */ X(fpcNm_E_MM_e) \
/* 0x1DE */ X(fpcNm_E_FZ_e) \
/* 0x1DF */ X(fpcNm_E_ZS_e) \
/* 0x1E0 */ X(fpcNm_E_KK_e) \
/* 0x1E1 */ X(fpcNm_E_HP_e) \
/* 0x1E2 */ X(fpcNm_E_ZH_e) \
/* 0x1E3 */ X(fpcNm_E_ZM_e) \
/* 0x1E4 */ X(fpcNm_E_PZ_e) \
/* 0x1E5 */ X(fpcNm_E_FB_e) \
/* 0x1E6 */ X(fpcNm_E_FK_e) \
/* 0x1E7 */ X(fpcNm_E_MS_e) \
/* 0x1E8 */ X(fpcNm_E_NEST_e) \
/* 0x1E9 */ X(fpcNm_E_NZ_e) \
/* 0x1EA */ X(fpcNm_E_BA_e) \
/* 0x1EB */ X(fpcNm_E_BU_e) \
/* 0x1EC */ X(fpcNm_E_BUG_e) \
/* 0x1ED */ X(fpcNm_E_BEE_e) \
/* 0x1EE */ X(fpcNm_E_IS_e) \
/* 0x1EF */ X(fpcNm_E_KG_e) \
/* 0x1F0 */ X(fpcNm_E_KR_e) \
/* 0x1F1 */ X(fpcNm_E_SW_e) \
/* 0x1F2 */ X(fpcNm_E_GE_e) \
/* 0x1F3 */ X(fpcNm_Tag_WatchGe_e) \
/* 0x1F4 */ X(fpcNm_E_YM_e) \
/* 0x1F5 */ X(fpcNm_E_YM_TAG_e) \
/* 0x1F6 */ X(fpcNm_E_YMB_e) \
/* 0x1F7 */ X(fpcNm_Tag_FWall_e) \
/* 0x1F8 */ X(fpcNm_Tag_WaterFall_e) \
/* 0x1F9 */ X(fpcNm_E_YK_e) \
/* 0x1FA */ X(fpcNm_E_YR_e) \
/* 0x1FB */ X(fpcNm_E_YG_e) \
/* 0x1FC */ X(fpcNm_E_HZ_e) \
/* 0x1FD */ X(fpcNm_E_WS_e) \
/* 0x1FE */ X(fpcNm_E_OC_e) \
/* 0x1FF */ X(fpcNm_E_OT_e) \
/* 0x200 */ X(fpcNm_E_DT_e) \
/* 0x201 */ X(fpcNm_E_BG_e) \
/* 0x202 */ X(fpcNm_E_OctBg_e) \
/* 0x203 */ X(fpcNm_DR_e) \
/* 0x204 */ X(fpcNm_L7lowDr_e) \
/* 0x205 */ X(fpcNm_L7ODR_e) \
/* 0x206 */ X(fpcNm_E_TT_e) \
/* 0x207 */ X(fpcNm_E_DK_e) \
/* 0x208 */ X(fpcNm_E_VT_e) \
/* 0x209 */ X(fpcNm_E_WW_e) \
/* 0x20A */ X(fpcNm_E_GI_e) \
/* 0x20B */ X(fpcNm_B_BH_e) \
/* 0x20C */ X(fpcNm_B_BQ_e) \
/* 0x20D */ X(fpcNm_B_GM_e) \
/* 0x20E */ X(fpcNm_B_GND_e) \
/* 0x20F */ X(fpcNm_B_GO_e) \
/* 0x210 */ X(fpcNm_B_OH2_e) \
/* 0x211 */ X(fpcNm_B_YO_e) \
/* 0x212 */ X(fpcNm_B_YOI_e) \
/* 0x213 */ X(fpcNm_B_TN_e) \
/* 0x214 */ X(fpcNm_B_GG_e) \
/* 0x215 */ X(fpcNm_B_DRE_e) \
/* 0x216 */ X(fpcNm_B_MGN_e) \
/* 0x217 */ X(fpcNm_E_WAP_e) \
/* 0x218 */ X(fpcNm_ITEM_e) \
/* 0x219 */ X(fpcNm_Obj_SmallKey_e) \
/* 0x21A */ X(fpcNm_Obj_Kantera_e) \
/* 0x21B */ X(fpcNm_Obj_LifeContainer_e) \
/* 0x21C */ X(fpcNm_Obj_Shield_e) \
/* 0x21D */ X(fpcNm_Demo_Item_e) \
/* 0x21E */ X(fpcNm_ShopItem_e) \
/* 0x21F */ X(fpcNm_Obj_Drop_e) \
/* 0x220 */ X(fpcNm_OBJ_RW_e) \
/* 0x221 */ X(fpcNm_NBOMB_e) \
/* 0x222 */ X(fpcNm_TAG_CSW_e) \
/* 0x223 */ X(fpcNm_TAG_QS_e) \
/* 0x224 */ X(fpcNm_HOZELDA_e) \
/* 0x225 */ X(fpcNm_SWC00_e) \
/* 0x226 */ X(fpcNm_KNOB20_e) \
/* 0x227 */ X(fpcNm_DBDOOR_e) \
/* 0x228 */ X(fpcNm_BOSS_DOOR_e) \
/* 0x229 */ X(fpcNm_L1BOSS_DOOR_e) \
/* 0x22A */ X(fpcNm_L1MBOSS_DOOR_e) \
/* 0x22B */ X(fpcNm_L5BOSS_DOOR_e) \
/* 0x22C */ X(fpcNm_DSHUTTER_e) \
/* 0x22D */ X(fpcNm_SPIRAL_DOOR_e) \
/* 0x22E */ X(fpcNm_Tag_ChgRestart_e) \
/* 0x22F */ X(fpcNm_Tag_Restart_e) \
/* 0x230 */ X(fpcNm_ANDSW_e) \
/* 0x231 */ X(fpcNm_ANDSW2_e) \
/* 0x232 */ X(fpcNm_MYNA_e) \
/* 0x233 */ X(fpcNm_NPC_GND_e) \
/* 0x234 */ X(fpcNm_NPC_GRA_e) \
/* 0x235 */ X(fpcNm_NPC_GRC_e) \
/* 0x236 */ X(fpcNm_NPC_GRD_e) \
/* 0x237 */ X(fpcNm_NPC_GRM_e) \
/* 0x238 */ X(fpcNm_NPC_GRMC_e) \
/* 0x239 */ X(fpcNm_NPC_GRO_e) \
/* 0x23A */ X(fpcNm_NPC_GRR_e) \
/* 0x23B */ X(fpcNm_NPC_GRS_e) \
/* 0x23C */ X(fpcNm_NPC_GRZ_e) \
/* 0x23D */ X(fpcNm_NPC_YAMID_e) \
/* 0x23E */ X(fpcNm_NPC_YAMIT_e) \
/* 0x23F */ X(fpcNm_NPC_YAMIS_e) \
/* 0x240 */ X(fpcNm_NPC_BLUENS_e) \
/* 0x241 */ X(fpcNm_NPC_KAKASHI_e) \
/* 0x242 */ X(fpcNm_NPC_KDK_e) \
/* 0x243 */ X(fpcNm_NPC_ARU_e) \
/* 0x244 */ X(fpcNm_NPC_BANS_e) \
/* 0x245 */ X(fpcNm_NPC_BESU_e) \
/* 0x246 */ X(fpcNm_NPC_BOU_e) \
/* 0x247 */ X(fpcNm_NPC_BOU_S_e) \
/* 0x248 */ X(fpcNm_NPC_CLERKA_e) \
/* 0x249 */ X(fpcNm_NPC_CLERKB_e) \
/* 0x24A */ X(fpcNm_NPC_CLERKT_e) \
/* 0x24B */ X(fpcNm_NPC_WRESTLER_e) \
/* 0x24C */ X(fpcNm_Tag_Arena_e) \
/* 0x24D */ X(fpcNm_Tag_Instruction_e) \
/* 0x24E */ X(fpcNm_NPC_DOC_e) \
/* 0x24F */ X(fpcNm_NPC_GWOLF_e) \
/* 0x250 */ X(fpcNm_NPC_LEN_e) \
/* 0x251 */ X(fpcNm_NPC_LUD_e) \
/* 0x252 */ X(fpcNm_NPC_FAIRY_SEIREI_e) \
/* 0x253 */ X(fpcNm_NPC_FAIRY_e) \
/* 0x254 */ X(fpcNm_NPC_HANJO_e) \
/* 0x255 */ X(fpcNm_NPC_HENNA_e) \
/* 0x256 */ X(fpcNm_NPC_HENNA0_e) \
/* 0x257 */ X(fpcNm_NPC_HOZ_e) \
/* 0x258 */ X(fpcNm_NPC_JAGAR_e) \
/* 0x259 */ X(fpcNm_NPC_KKRI_e) \
/* 0x25A */ X(fpcNm_NPC_KN_e) \
/* 0x25B */ X(fpcNm_KN_BULLET_e) \
/* 0x25C */ X(fpcNm_NPC_KNJ_e) \
/* 0x25D */ X(fpcNm_NPC_KOLIN_e) \
/* 0x25E */ X(fpcNm_NPC_KOLINB_e) \
/* 0x25F */ X(fpcNm_NPC_KYURY_e) \
/* 0x260 */ X(fpcNm_NPC_MARO_e) \
/* 0x261 */ X(fpcNm_NPC_MIDP_e) \
/* 0x262 */ X(fpcNm_NPC_MOI_e) \
/* 0x263 */ X(fpcNm_NPC_RACA_e) \
/* 0x264 */ X(fpcNm_NPC_SARU_e) \
/* 0x265 */ X(fpcNm_NPC_SEIB_e) \
/* 0x266 */ X(fpcNm_NPC_SEIC_e) \
/* 0x267 */ X(fpcNm_NPC_SEID_e) \
/* 0x268 */ X(fpcNm_NPC_SEIRA_e) \
/* 0x269 */ X(fpcNm_NPC_SERA2_e) \
/* 0x26A */ X(fpcNm_NPC_SEIREI_e) \
/* 0x26B */ X(fpcNm_NPC_SHAMAN_e) \
/* 0x26C */ X(fpcNm_NPC_SMARO_e) \
/* 0x26D */ X(fpcNm_NPC_SOLA_e) \
/* 0x26E */ X(fpcNm_NPC_TARO_e) \
/* 0x26F */ X(fpcNm_NPC_PACHI_BESU_e) \
/* 0x270 */ X(fpcNm_NPC_PACHI_TARO_e) \
/* 0x271 */ X(fpcNm_NPC_PACHI_MARO_e) \
/* 0x272 */ X(fpcNm_TAG_PATI_e) \
/* 0x273 */ X(fpcNm_NPC_THE_e) \
/* 0x274 */ X(fpcNm_NPC_TKJ_e) \
/* 0x275 */ X(fpcNm_NPC_TKS_e) \
/* 0x276 */ X(fpcNm_NPC_TKC_e) \
/* 0x277 */ X(fpcNm_OBJ_TKS_e) \
/* 0x278 */ X(fpcNm_NPC_TOBY_e) \
/* 0x279 */ X(fpcNm_NPC_URI_e) \
/* 0x27A */ X(fpcNm_NPC_YELIA_e) \
/* 0x27B */ X(fpcNm_NPC_YKM_e) \
/* 0x27C */ X(fpcNm_NPC_YKW_e) \
/* 0x27D */ X(fpcNm_NPC_ZANB_e) \
/* 0x27E */ X(fpcNm_NPC_ZANT_e) \
/* 0x27F */ X(fpcNm_NPC_ZELDA_e) \
/* 0x280 */ X(fpcNm_NPC_ZELR_e) \
/* 0x281 */ X(fpcNm_NPC_ZELRO_e) \
/* 0x282 */ X(fpcNm_OBJ_ZRAFREEZE_e) \
/* 0x283 */ X(fpcNm_NPC_ZRC_e) \
/* 0x284 */ X(fpcNm_NPC_ZRZ_e) \
/* 0x285 */ X(fpcNm_ZRA_MARK_e) \
/* 0x286 */ X(fpcNm_MYNA2_e) \
/* 0x287 */ X(fpcNm_TAG_MYNA2_e) \
/* 0x288 */ X(fpcNm_NPC_CD3_e) \
/* 0x289 */ X(fpcNm_Tag_Schedule_e) \
/* 0x28A */ X(fpcNm_Tag_Escape_e) \
/* 0x28B */ X(fpcNm_NPC_CHAT_e) \
/* 0x28C */ X(fpcNm_NPC_SOLDIERa_e) \
/* 0x28D */ X(fpcNm_NPC_SOLDIERb_e) \
/* 0x28E */ X(fpcNm_PASSER_MNG_e) \
/* 0x28F */ X(fpcNm_NPC_PASSER_e) \
/* 0x290 */ X(fpcNm_NPC_PASSER2_e) \
/* 0x291 */ X(fpcNm_NPC_POST_e) \
/* 0x292 */ X(fpcNm_NPC_POUYA_e) \
/* 0x293 */ X(fpcNm_FORMATION_MNG_e) \
/* 0x294 */ X(fpcNm_NPC_FGUARD_e) \
/* 0x295 */ X(fpcNm_GUARD_MNG_e) \
/* 0x296 */ X(fpcNm_TAG_GUARD_e) \
/* 0x297 */ X(fpcNm_NPC_GUARD_e) \
/* 0x298 */ X(fpcNm_NPC_ASH_e) \
/* 0x299 */ X(fpcNm_NPC_ASHB_e) \
/* 0x29A */ X(fpcNm_NPC_SHAD_e) \
/* 0x29B */ X(fpcNm_NPC_RAFREL_e) \
/* 0x29C */ X(fpcNm_NPC_MOIR_e) \
/* 0x29D */ X(fpcNm_NPC_IMPAL_e) \
/* 0x29E */ X(fpcNm_NPC_SHOE_e) \
/* 0x29F */ X(fpcNm_NPC_DOORBOY_e) \
/* 0x2A0 */ X(fpcNm_NPC_PRAYER_e) \
/* 0x2A1 */ X(fpcNm_NPC_KASIHANA_e) \
/* 0x2A2 */ X(fpcNm_NPC_KASIKYU_e) \
/* 0x2A3 */ X(fpcNm_NPC_KASIMICH_e) \
/* 0x2A4 */ X(fpcNm_NPC_DRSOL_e) \
/* 0x2A5 */ X(fpcNm_NPC_CHIN_e) \
/* 0x2A6 */ X(fpcNm_NPC_INS_e) \
/* 0x2A7 */ X(fpcNm_NPC_SHOP0_e) \
/* 0x2A8 */ X(fpcNm_NPC_MK_e) \
/* 0x2A9 */ X(fpcNm_NPC_P2_e) \
/* 0x2AA */ X(fpcNm_KYTAG00_e) \
/* 0x2AB */ X(fpcNm_KYTAG01_e) \
/* 0x2AC */ X(fpcNm_KYTAG02_e) \
/* 0x2AD */ X(fpcNm_KYTAG03_e) \
/* 0x2AE */ X(fpcNm_KYTAG04_e) \
/* 0x2AF */ X(fpcNm_KYTAG05_e) \
/* 0x2B0 */ X(fpcNm_KYTAG06_e) \
/* 0x2B1 */ X(fpcNm_KYTAG07_e) \
/* 0x2B2 */ X(fpcNm_KYTAG08_e) \
/* 0x2B3 */ X(fpcNm_KYTAG09_e) \
/* 0x2B4 */ X(fpcNm_KYTAG10_e) \
/* 0x2B5 */ X(fpcNm_KYTAG11_e) \
/* 0x2B6 */ X(fpcNm_KYTAG12_e) \
/* 0x2B7 */ X(fpcNm_KYTAG13_e) \
/* 0x2B8 */ X(fpcNm_KYTAG14_e) \
/* 0x2B9 */ X(fpcNm_KYTAG15_e) \
/* 0x2BA */ X(fpcNm_KYTAG16_e) \
/* 0x2BB */ X(fpcNm_KYTAG17_e) \
/* 0x2BC */ X(fpcNm_Ykgr_e) \
/* 0x2BD */ X(fpcNm_TALK_e) \
/* 0x2BE */ X(fpcNm_Obj_Crope_e) \
/* 0x2BF */ X(fpcNm_Obj_Bombf_e) \
/* 0x2C0 */ X(fpcNm_Obj_BkLeaf_e) \
/* 0x2C1 */ X(fpcNm_Tag_Mhint_e) \
/* 0x2C2 */ X(fpcNm_Tag_Mmsg_e) \
/* 0x2C3 */ X(fpcNm_Tag_Mwait_e) \
/* 0x2C4 */ X(fpcNm_Tag_Mstop_e) \
/* 0x2C5 */ X(fpcNm_Tag_Stream_e) \
/* 0x2C6 */ X(fpcNm_Tag_Sppath_e) \
/* 0x2C7 */ X(fpcNm_Tag_Wljump_e) \
/* 0x2C8 */ X(fpcNm_Tag_TWGate_e) \
/* 0x2C9 */ X(fpcNm_Tag_Lv6Gate_e) \
/* 0x2CA */ X(fpcNm_Tag_Lv7Gate_e) \
/* 0x2CB */ X(fpcNm_Tag_Lv8Gate_e) \
/* 0x2CC */ X(fpcNm_Tag_TheBHint_e) \
/* 0x2CD */ X(fpcNm_Tag_Assist_e) \
/* 0x2CE */ X(fpcNm_DEMO00_e) \
/* 0x2CF */ X(fpcNm_TAG_CAMERA_e) \
/* 0x2D0 */ X(fpcNm_TAG_CHKPOINT_e) \
/* 0x2D1 */ X(fpcNm_TAG_EVENT_e) \
/* 0x2D2 */ X(fpcNm_TAG_EVT_e) \
/* 0x2D3 */ X(fpcNm_TAG_TELOP_e) \
/* 0x2D4 */ X(fpcNm_TAG_HOWL_e) \
/* 0x2D5 */ X(fpcNm_TAG_MSG_e) \
/* 0x2D6 */ X(fpcNm_TAG_LANTERN_e) \
/* 0x2D7 */ X(fpcNm_Tag_Mist_e) \
/* 0x2D8 */ X(fpcNm_DMIDNA_e) \
/* 0x2D9 */ X(fpcNm_KY_THUNDER_e) \
/* 0x2DA */ X(fpcNm_VRBOX_e) \
/* 0x2DB */ X(fpcNm_VRBOX2_e) \
/* 0x2DC */ X(fpcNm_BG_e) \
/* 0x2DD */ X(fpcNm_SET_BG_OBJ_e) \
/* 0x2DE */ X(fpcNm_BG_OBJ_e) \
/* 0x2DF */ X(fpcNm_MIRROR_e) \
/* 0x2E0 */ X(fpcNm_MOVIE_PLAYER_e) \
/* 0x2E1 */ X(fpcNm_TITLE_e) \
/* 0x2E2 */ X(fpcNm_FR_e) \
/* 0x2E3 */ X(fpcNm_ECONT_e) \
/* 0x2E4 */ X(fpcNm_MG_ROD_e) \
/* 0x2E5 */ X(fpcNm_E_ARROW_e) \
/* 0x2E6 */ X(fpcNm_BULLET_e) \
/* 0x2E7 */ X(fpcNm_SWHIT0_e) \
/* 0x2E8 */ X(fpcNm_E_TH_BALL_e) \
/* 0x2E9 */ X(fpcNm_TAG_EVTAREA_e) \
/* 0x2EA */ X(fpcNm_TAG_EVTMSG_e) \
/* 0x2EB */ X(fpcNm_TAG_KMSG_e) \
/* 0x2EC */ X(fpcNm_TAG_PUSH_e) \
/* 0x2ED */ X(fpcNm_E_MK_BO_e) \
/* 0x2EE */ X(fpcNm_E_MM_MT_e) \
/* 0x2EF */ X(fpcNm_OBJ_KBOX_e) \
/* 0x2F0 */ X(fpcNm_OBJ_FW_e) \
/* 0x2F1 */ X(fpcNm_B_GOS_e) \
/* 0x2F2 */ X(fpcNm_OBJ_YSTONE_e) \
/* 0x2F3 */ X(fpcNm_MANT_e) \
/* 0x2F4 */ X(fpcNm_CROD_e) \
/* 0x2F5 */ X(fpcNm_OBJ_PLEAF_e) \
/* 0x2F6 */ X(fpcNm_OBJ_KBACKET_e) \
/* 0x2F7 */ X(fpcNm_OBJ_YBAG_e) \
/* 0x2F8 */ X(fpcNm_OBJ_PUMPKIN_e) \
/* 0x2F9 */ X(fpcNm_OBJ_AUTOMATA_e) \
/* 0x2FA */ X(fpcNm_OBJ_GADGET_e) \
/* 0x2FB */ X(fpcNm_OBJ_KAGO_e) \
/* 0x2FC */ X(fpcNm_Obj_Carry_e) \
/* 0x2FD */ X(fpcNm_Obj_Stone_e) \
/* 0x2FE */ X(fpcNm_OBJ_HB_e) \
/* 0x2FF */ X(fpcNm_NPC_INKO_e) \
/* 0x300 */ X(fpcNm_BD_e) \
/* 0x301 */ X(fpcNm_Obj_Eff_e) \
/* 0x302 */ X(fpcNm_WPILLAR_e) \
/* 0x303 */ X(fpcNm_WMARK_e) \
/* 0x304 */ X(fpcNm_E_BI_e) \
/* 0x305 */ X(fpcNm_E_BI_LEAF_e) \
/* 0x306 */ X(fpcNm_START_AND_GOAL_e) \
/* 0x307 */ X(fpcNm_NPC_DF_e) \
/* 0x308 */ X(fpcNm_ARROW_e) \
/* 0x309 */ X(fpcNm_PATH_LINE_e) \
/* 0x30A */ X(fpcNm_TAG_ALLMATO_e) \
/* 0x30B */ X(fpcNm_Obj_Timer_e) \
/* 0x30C */ X(fpcNm_SCENE_EXIT_e) \
/* 0x30D */ X(fpcNm_CAMERA_e) \
/* 0x30E */ X(fpcNm_CAMERA2_e) \
/* 0x30F */ X(fpcNm_SUSPEND_e) \
/* 0x310 */ X(fpcNm_GRASS_e) \
/* 0x311 */ X(fpcNm_KYEFF_e) \
/* 0x312 */ X(fpcNm_KYEFF2_e) \
/* 0x313 */ X(fpcNm_MSG_OBJECT_e) \
/* 0x314 */ X(fpcNm_MENUWINDOW_e) \
/* 0x315 */ X(fpcNm_TIMER_e) \
/* 0x316 */ X(fpcNm_METER2_e) \
/* 0x317 */ X(fpcNm_GAMEOVER_e) \

#define X(name) name,
enum {
    ALL_PROCS

    fpcNm_MAX_NUM,
};
#undef X

#if PROCS_DUMP_NAMES
struct ProcName {
    unsigned int id;
    const char* name;
};

#define X(name) { name, #name },
inline const ProcName procNames[] = {
    ALL_PROCS
};
#undef X

inline const char* GetProcName(unsigned int id) {
    for (auto procName : procNames) {
        if (procName.id == id) {
            return procName.name;
        }
    }

    return nullptr;
}

#endif

#undef ALL_PROCS

#endif /* F_PC_NAME_H_ */
